# Generated by Django 5.0.6 on 2024-05-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('wait', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('total_time', models.IntegerField()),
            ],
        ),
    ]
